# --- BACKEND Y VSYNC
# Usamos glx porque en Intel es más eficiente para evitar el tearing
backend = "glx";
vsync = true;

# --- DESACTIVAR TODO LO DEMÁS
shadow = false;          # Sin sombras
fading = false;          # Sin efectos de aparecer/desaparecer
inactive-opacity = 1.0;  # Sin transparencias en ventanas inactivas
frame-opacity = 1.0;     # Sin transparencias en los marcos

# --- SOLUCIÓN AL ERROR DE GLX ---
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;       # Solo redibuja lo que cambió (ahorra batería)