# --- BACKEND Y VSYNC
# Usamos glx porque en Intel es más eficiente para evitar el tearing
backend = "glx";
vsync = true;

# --- DESACTIVAR TODO LO DEMÁS
shadow = false;          # Sin sombras
fading = false;          # Sin efectos de aparecer/desaparecer
inactive-opacity = 1.0;  # Sin transparencias en ventanas inactivas
frame-opacity = 1.0;     # Sin transparencias en los marcos

# --- SOLUCIÓN AL ERROR DE GLX ---
use-damage = true;       # Solo redibuja lo que cambió (ahorra batería)

mark-wmwin-focused = true;
mark-ovlp-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;